### ISSUE TITLE
The 'not equal' operator does not generate valid sql for postgres

### ISSUE THREAD

**Issue by glasseyes42** [panates/sqb#27]
https://github.com/panates/sqb/blob/master/docs/query-builder/operators.md#opne

`NOT = ...` is not valid syntax for postgres, needs to be one of `!=` or `<>`

See: https://www.postgresql.org/docs/current/static/functions-comparison.html

(Thanks by the way - great library)

**Comment by erayhanoglu** [comment]
Hello,
Thank you for your valuable feedback. Actually SQB is an abstract library and examples in the document may not suit for all dialects. By the way, because != is more common, i have changed the example.

The point is, i ve chacked sqb-serializer-pg and noticed that it was working wrong. Corrected the problem and released SQB and all sub projects.

**Comment by glasseyes42** [comment]
Thanks so much - having submitted this, in my local hacking I had traced a possible solution to the pg-serializer. Will take a look in the morning.
